"""institution website and headquarters

Revision ID: 291dfd768085
Revises: cd710e3047cb
Create Date: 2026-08-22 16:07:57.058323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '291dfd768085'
down_revision: Union[str, None] = 'cd710e3047cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('headquarters', sa.String(length=255), nullable=True))
    op.add_column('institution', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'website')
    op.drop_column('institution', 'headquarters')
    # ### end Alembic commands ###
