"""initial schema

Revision ID: a1f4860dbd3f
Revises: 
Create Date: 2026-08-22 15:53:44.912452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1f4860dbd3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('group_holdco_id', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('sector_tag', sa.String(length=50), nullable=True),
    sa.Column('cbn_authorization', sa.String(length=50), nullable=True),
    sa.Column('ngx_ticker', sa.String(length=20), nullable=True),
    sa.Column('ngx_listed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('institution_code', sa.String(length=50), nullable=True),
    sa.Column('institution_type', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_holdco_id'], ['institution.institution_id'], ),
    sa.PrimaryKeyConstraint('institution_id'),
    sa.UniqueConstraint('institution_code')
    )
    op.create_table('party',
    sa.Column('party_id', sa.String(length=64), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('customer_reference', sa.String(length=100), nullable=True),
    sa.Column('relationship_start_date', sa.Date(), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state_code', sa.String(length=20), nullable=True),
    sa.Column('lga_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('party_id')
    )
    op.create_table('reporting_submission',
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=30), nullable=False),
    sa.Column('destination_schema_version', sa.String(length=20), nullable=False),
    sa.Column('reporting_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('control_total', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('deal',
    sa.Column('deal_id', sa.String(length=64), nullable=False),
    sa.Column('originator_institution_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('deal_stage', sa.String(length=20), nullable=False),
    sa.Column('spv_name', sa.String(length=255), nullable=True),
    sa.Column('senior_tranche_size', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('equity_tranche_size', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['originator_institution_id'], ['institution.institution_id'], ),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('fccpc_digital_lender',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('app_or_entity_name', sa.String(length=255), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=True),
    sa.Column('institution_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_date', sa.Date(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filing',
    sa.Column('filing_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('extraction_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.PrimaryKeyConstraint('filing_id')
    )
    op.create_table('organisation',
    sa.Column('party_id', sa.String(length=64), nullable=False),
    sa.Column('tin', sa.String(length=50), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('business_type_code', sa.String(length=30), nullable=True),
    sa.Column('sector_code', sa.String(length=50), nullable=True),
    sa.Column('industry_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.party_id'], ),
    sa.PrimaryKeyConstraint('party_id')
    )
    op.create_table('person',
    sa.Column('party_id', sa.String(length=64), nullable=False),
    sa.Column('bvn', sa.String(length=11), nullable=True),
    sa.Column('nin', sa.String(length=11), nullable=True),
    sa.Column('surname', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('middle_name', sa.String(length=150), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('nationality_code', sa.String(length=2), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('occupation_code', sa.String(length=30), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.party_id'], ),
    sa.PrimaryKeyConstraint('party_id')
    )
    op.create_table('loan_tape_snapshot',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deal_id', sa.String(length=64), nullable=True),
    sa.Column('institution_id', sa.String(length=100), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.DateTime(), nullable=False),
    sa.Column('nda_reference', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mapping_json', sa.Text(), nullable=True),
    sa.Column('wcds_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.deal_id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provenance',
    sa.Column('provenance_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieved_date', sa.Date(), nullable=True),
    sa.Column('extraction_method', sa.String(length=30), nullable=True),
    sa.Column('extracted_by', sa.String(length=150), nullable=True),
    sa.Column('confidence_score', sa.String(length=10), nullable=True),
    sa.Column('self_reported', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=150), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['filing.filing_id'], ),
    sa.PrimaryKeyConstraint('provenance_id')
    )
    op.create_table('related_party',
    sa.Column('related_party_id', sa.String(length=64), nullable=False),
    sa.Column('organisation_party_id', sa.String(length=64), nullable=False),
    sa.Column('person_party_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_role', sa.String(length=30), nullable=False),
    sa.Column('ownership_percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_party_id'], ['organisation.party_id'], ),
    sa.ForeignKeyConstraint(['person_party_id'], ['person.party_id'], ),
    sa.PrimaryKeyConstraint('related_party_id')
    )
    op.create_table('capital_market_instrument',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('instrument_type', sa.String(length=30), nullable=True),
    sa.Column('issue_size', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('tenor', sa.String(length=30), nullable=True),
    sa.Column('coupon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('use_of_proceeds', sa.Text(), nullable=True),
    sa.Column('collateral_description', sa.Text(), nullable=True),
    sa.Column('sec_rin', sa.String(length=50), nullable=True),
    sa.Column('trustee', sa.String(length=150), nullable=True),
    sa.Column('issuing_house', sa.String(length=150), nullable=True),
    sa.Column('provenance_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.provenance_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disbursement_metric',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('disbursement_volume', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('active_customers', sa.Integer(), nullable=True),
    sa.Column('avg_ticket_size', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('portfolio_at_risk', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('self_reported', sa.Boolean(), nullable=False),
    sa.Column('provenance_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.provenance_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facility',
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('source_facility_id', sa.String(length=150), nullable=False),
    sa.Column('crms_credit_id', sa.String(length=150), nullable=True),
    sa.Column('account_reference', sa.String(length=150), nullable=True),
    sa.Column('facility_type', sa.String(length=30), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('approved_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('original_principal', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('amount_disbursed', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('origination_date', sa.Date(), nullable=False),
    sa.Column('first_disbursement_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('original_tenor_days', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('rate_type', sa.String(length=20), nullable=True),
    sa.Column('repayment_frequency', sa.String(length=20), nullable=True),
    sa.Column('scheduled_payment_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('purpose_code', sa.String(length=50), nullable=True),
    sa.Column('sector_code', sa.String(length=50), nullable=True),
    sa.Column('funding_source_code', sa.String(length=50), nullable=True),
    sa.Column('secured_flag', sa.Boolean(), nullable=False),
    sa.Column('facility_status', sa.String(length=20), nullable=False),
    sa.Column('loan_tape_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['loan_tape_snapshot_id'], ['loan_tape_snapshot.id'], ),
    sa.PrimaryKeyConstraint('facility_id'),
    sa.UniqueConstraint('institution_id', 'source_facility_id', name='uq_facility_source_id')
    )
    op.create_table('industry_aggregate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('sectoral_breakdown', sa.Text(), nullable=True),
    sa.Column('npl_ratio_industry', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('provenance_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.provenance_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_mix',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('dimension_type', sa.String(length=30), nullable=False),
    sa.Column('dimension_value', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('pct_of_book', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('provenance_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.provenance_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_loans', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('net_loans', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('stage_1_balance', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('stage_2_balance', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('stage_3_balance', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('npl_ratio', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('npl_coverage', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('avg_yield_on_loans', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('cost_of_funds', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('provisioning_charge', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('provenance_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.provenance_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('min_ticket', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('max_ticket', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tenor_range', sa.String(length=50), nullable=True),
    sa.Column('indicative_rate_range', sa.String(length=50), nullable=True),
    sa.Column('eligibility_notes', sa.Text(), nullable=True),
    sa.Column('collateral_required', sa.Boolean(), nullable=True),
    sa.Column('scrape_date', sa.Date(), nullable=True),
    sa.Column('provenance_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.provenance_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating_action',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('agency', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('outlook', sa.String(length=20), nullable=True),
    sa.Column('prior_rating', sa.String(length=20), nullable=True),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('key_commentary_tags', sa.Text(), nullable=True),
    sa.Column('provenance_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.provenance_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation',
    sa.Column('reconciliation_id', sa.String(length=64), nullable=False),
    sa.Column('loan_tape_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('control_name', sa.String(length=100), nullable=False),
    sa.Column('source_control_total', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('wcds_control_total', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('within_tolerance', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_tape_snapshot_id'], ['loan_tape_snapshot.id'], ),
    sa.PrimaryKeyConstraint('reconciliation_id')
    )
    op.create_table('source_record',
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('loan_tape_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('source_system', sa.String(length=150), nullable=False),
    sa.Column('source_table', sa.String(length=150), nullable=True),
    sa.Column('source_primary_key', sa.String(length=500), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_tape_snapshot_id'], ['loan_tape_snapshot.id'], ),
    sa.PrimaryKeyConstraint('source_record_id')
    )
    op.create_table('spv',
    sa.Column('spv_id', sa.String(length=64), nullable=False),
    sa.Column('deal_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('loan_tape_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('eligible_pool_par', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('eligible_facility_count', sa.Integer(), nullable=True),
    sa.Column('weighted_avg_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('weighted_avg_life_months', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('weighted_avg_dpd', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('eligibility_criteria_json', sa.Text(), nullable=True),
    sa.Column('sizing_assumptions_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.deal_id'], ),
    sa.ForeignKeyConstraint(['loan_tape_snapshot_id'], ['loan_tape_snapshot.id'], ),
    sa.PrimaryKeyConstraint('spv_id')
    )
    op.create_table('validation_result',
    sa.Column('validation_result_id', sa.String(length=64), nullable=False),
    sa.Column('loan_tape_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=150), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_tape_snapshot_id'], ['loan_tape_snapshot.id'], ),
    sa.PrimaryKeyConstraint('validation_result_id')
    )
    op.create_table('collateral',
    sa.Column('collateral_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('collateral_type_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('original_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('perfection_status', sa.String(length=20), nullable=True),
    sa.Column('security_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.facility_id'], ),
    sa.PrimaryKeyConstraint('collateral_id')
    )
    op.create_table('credit_risk',
    sa.Column('credit_risk_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('ifrs9_stage', sa.String(length=10), nullable=True),
    sa.Column('sicr_flag', sa.Boolean(), nullable=True),
    sa.Column('pd_12m', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('pd_lifetime', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('lgd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('ead', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ecl_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.facility_id'], ),
    sa.PrimaryKeyConstraint('credit_risk_id'),
    sa.UniqueConstraint('facility_id', 'assessment_date', name='uq_credit_risk_facility_date')
    )
    op.create_table('facility_party',
    sa.Column('facility_party_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('party_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('liability_percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.facility_id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.party_id'], ),
    sa.PrimaryKeyConstraint('facility_party_id')
    )
    op.create_table('facility_snapshot',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('opening_principal_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('outstanding_principal', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('accrued_interest', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fees_outstanding', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_exposure', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('past_due_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('days_past_due', sa.Integer(), nullable=False),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('delinquency_bucket', sa.String(length=20), nullable=False),
    sa.Column('default_flag', sa.Boolean(), nullable=False),
    sa.Column('default_date', sa.Date(), nullable=True),
    sa.Column('restructure_flag', sa.Boolean(), nullable=False),
    sa.Column('writeoff_flag', sa.Boolean(), nullable=False),
    sa.Column('writeoff_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('recovery_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('month_end_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.facility_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('facility_id', 'snapshot_date', 'snapshot_type', name='uq_snapshot_facility_date_type')
    )
    op.create_table('guarantee',
    sa.Column('guarantee_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('guarantor_party_id', sa.String(length=64), nullable=False),
    sa.Column('guarantee_type', sa.String(length=20), nullable=False),
    sa.Column('guarantee_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.facility_id'], ),
    sa.ForeignKeyConstraint(['guarantor_party_id'], ['party.party_id'], ),
    sa.PrimaryKeyConstraint('guarantee_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=150), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('principal_component', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('interest_component', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fee_component', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('recovery_component', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('reversal_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.facility_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('pool_facility',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('spv_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reasons', sa.Text(), nullable=True),
    sa.Column('pool_par_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.facility_id'], ),
    sa.ForeignKeyConstraint(['spv_id'], ['spv.spv_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restructure',
    sa.Column('restructure_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('restructure_date', sa.Date(), nullable=False),
    sa.Column('restructure_type', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('previous_principal_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revised_principal_balance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('previous_interest_rate', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('revised_interest_rate', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('previous_maturity_date', sa.Date(), nullable=True),
    sa.Column('revised_maturity_date', sa.Date(), nullable=True),
    sa.Column('capitalised_interest', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.facility_id'], ),
    sa.PrimaryKeyConstraint('restructure_id')
    )
    op.create_table('schedule',
    sa.Column('schedule_item_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fees_due', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.facility_id'], ),
    sa.PrimaryKeyConstraint('schedule_item_id')
    )
    op.create_table('tranche',
    sa.Column('tranche_id', sa.String(length=64), nullable=False),
    sa.Column('spv_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('seniority_rank', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('coupon_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('advance_rate', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spv_id'], ['spv.spv_id'], ),
    sa.PrimaryKeyConstraint('tranche_id')
    )
    op.create_table('transformation_event',
    sa.Column('transformation_event_id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('target_entity', sa.String(length=100), nullable=False),
    sa.Column('target_field', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('normalised_value', sa.Text(), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.source_record_id'], ),
    sa.PrimaryKeyConstraint('transformation_event_id')
    )
    op.create_table('waterfall_run',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('spv_id', sa.String(length=64), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('assumptions_json', sa.Text(), nullable=True),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('senior_fully_repaid_month', sa.Integer(), nullable=True),
    sa.Column('mezz_fully_repaid_month', sa.Integer(), nullable=True),
    sa.Column('equity_irr', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('senior_dscr_min', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spv_id'], ['spv.spv_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('waterfall_period',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('period_index', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('collections_principal', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('collections_interest', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('defaults', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('recoveries', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('servicing_fee', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('senior_interest_paid', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('senior_principal_paid', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('senior_balance_end', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('mezz_interest_paid', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('mezz_principal_paid', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('mezz_balance_end', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('equity_distribution', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pool_balance_end', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['waterfall_run.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waterfall_period')
    op.drop_table('waterfall_run')
    op.drop_table('transformation_event')
    op.drop_table('tranche')
    op.drop_table('schedule')
    op.drop_table('restructure')
    op.drop_table('pool_facility')
    op.drop_table('payment')
    op.drop_table('guarantee')
    op.drop_table('facility_snapshot')
    op.drop_table('facility_party')
    op.drop_table('credit_risk')
    op.drop_table('collateral')
    op.drop_table('validation_result')
    op.drop_table('spv')
    op.drop_table('source_record')
    op.drop_table('reconciliation')
    op.drop_table('rating_action')
    op.drop_table('product_snapshot')
    op.drop_table('portfolio_snapshot')
    op.drop_table('portfolio_mix')
    op.drop_table('industry_aggregate')
    op.drop_table('facility')
    op.drop_table('disbursement_metric')
    op.drop_table('capital_market_instrument')
    op.drop_table('related_party')
    op.drop_table('provenance')
    op.drop_table('loan_tape_snapshot')
    op.drop_table('person')
    op.drop_table('organisation')
    op.drop_table('filing')
    op.drop_table('fccpc_digital_lender')
    op.drop_table('deal')
    op.drop_table('reporting_submission')
    op.drop_table('party')
    op.drop_table('institution')
    # ### end Alembic commands ###
