"""widen rating fields

Revision ID: c17443101dd9
Revises: e66463e9d317
Create Date: 2026-08-22 16:08:32.384442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c17443101dd9'
down_revision: Union[str, None] = 'e66463e9d317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating_action', 'rating',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('rating_action', 'prior_rating',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating_action', 'prior_rating',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('rating_action', 'rating',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
