"""tier1 fact tables match seed json shape

Revision ID: cd710e3047cb
Revises: a1f4860dbd3f
Create Date: 2026-08-22 16:07:05.844327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd710e3047cb'
down_revision: Union[str, None] = 'a1f4860dbd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capital_market_instrument', sa.Column('issuer_name', sa.String(length=255), nullable=True))
    op.add_column('capital_market_instrument', sa.Column('series', sa.String(length=150), nullable=True))
    op.add_column('capital_market_instrument', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('capital_market_instrument', sa.Column('issue_date', sa.Date(), nullable=True))
    op.add_column('capital_market_instrument', sa.Column('confidence', sa.String(length=10), nullable=True))
    op.add_column('capital_market_instrument', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('capital_market_instrument', sa.Column('source_name', sa.Text(), nullable=True))
    op.add_column('capital_market_instrument', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('capital_market_instrument', sa.Column('retrieved_date', sa.Date(), nullable=True))
    op.alter_column('capital_market_instrument', 'issue_size',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.drop_constraint(op.f('capital_market_instrument_provenance_id_fkey'), 'capital_market_instrument', type_='foreignkey')
    op.drop_column('capital_market_instrument', 'provenance_id')
    op.add_column('disbursement_metric', sa.Column('period_type', sa.String(length=10), nullable=True))
    op.add_column('disbursement_metric', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('disbursement_metric', sa.Column('metric_description', sa.Text(), nullable=True))
    op.add_column('disbursement_metric', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('disbursement_metric', sa.Column('source_name', sa.Text(), nullable=True))
    op.add_column('disbursement_metric', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('disbursement_metric', sa.Column('retrieved_date', sa.Date(), nullable=True))
    op.alter_column('disbursement_metric', 'disbursement_volume',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.drop_constraint(op.f('disbursement_metric_provenance_id_fkey'), 'disbursement_metric', type_='foreignkey')
    op.drop_column('disbursement_metric', 'provenance_id')
    op.add_column('industry_aggregate', sa.Column('metric', sa.String(length=100), nullable=False))
    op.add_column('industry_aggregate', sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=True))
    op.add_column('industry_aggregate', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('industry_aggregate', sa.Column('confidence', sa.String(length=10), nullable=True))
    op.add_column('industry_aggregate', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('industry_aggregate', sa.Column('source_name', sa.Text(), nullable=True))
    op.add_column('industry_aggregate', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('industry_aggregate', sa.Column('retrieved_date', sa.Date(), nullable=True))
    op.drop_constraint(op.f('industry_aggregate_provenance_id_fkey'), 'industry_aggregate', type_='foreignkey')
    op.drop_column('industry_aggregate', 'npl_ratio_industry')
    op.drop_column('industry_aggregate', 'source')
    op.drop_column('industry_aggregate', 'sectoral_breakdown')
    op.drop_column('industry_aggregate', 'total_credit')
    op.drop_column('industry_aggregate', 'provenance_id')
    op.add_column('portfolio_mix', sa.Column('confidence', sa.String(length=10), nullable=True))
    op.add_column('portfolio_mix', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('portfolio_mix', sa.Column('source_name', sa.Text(), nullable=True))
    op.add_column('portfolio_mix', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('portfolio_mix', sa.Column('retrieved_date', sa.Date(), nullable=True))
    op.alter_column('portfolio_mix', 'amount',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.drop_constraint(op.f('portfolio_mix_provenance_id_fkey'), 'portfolio_mix', type_='foreignkey')
    op.drop_column('portfolio_mix', 'provenance_id')
    op.add_column('portfolio_snapshot', sa.Column('period_type', sa.String(length=10), nullable=True))
    op.add_column('portfolio_snapshot', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('portfolio_snapshot', sa.Column('confidence', sa.String(length=10), nullable=True))
    op.add_column('portfolio_snapshot', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('portfolio_snapshot', sa.Column('source_name', sa.Text(), nullable=True))
    op.add_column('portfolio_snapshot', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('portfolio_snapshot', sa.Column('retrieved_date', sa.Date(), nullable=True))
    op.alter_column('portfolio_snapshot', 'gross_loans',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'net_loans',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'stage_1_balance',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'stage_2_balance',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'stage_3_balance',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'provisioning_charge',
               existing_type=sa.NUMERIC(precision=24, scale=2),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.drop_constraint(op.f('portfolio_snapshot_provenance_id_fkey'), 'portfolio_snapshot', type_='foreignkey')
    op.drop_column('portfolio_snapshot', 'provenance_id')
    op.add_column('product_snapshot', sa.Column('ticket_currency', sa.String(length=3), nullable=True))
    op.add_column('product_snapshot', sa.Column('min_tenor_days', sa.Integer(), nullable=True))
    op.add_column('product_snapshot', sa.Column('max_tenor_days', sa.Integer(), nullable=True))
    op.add_column('product_snapshot', sa.Column('interest_rate_description', sa.Text(), nullable=True))
    op.add_column('product_snapshot', sa.Column('confidence', sa.String(length=10), nullable=True))
    op.add_column('product_snapshot', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('product_snapshot', sa.Column('source_name', sa.Text(), nullable=True))
    op.add_column('product_snapshot', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('product_snapshot', sa.Column('retrieved_date', sa.Date(), nullable=True))
    op.alter_column('product_snapshot', 'product_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('product_snapshot', 'collateral_required',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('product_snapshot_provenance_id_fkey'), 'product_snapshot', type_='foreignkey')
    op.drop_column('product_snapshot', 'indicative_rate_range')
    op.drop_column('product_snapshot', 'tenor_range')
    op.drop_column('product_snapshot', 'provenance_id')
    op.add_column('rating_action', sa.Column('action_date_is_estimated', sa.Boolean(), nullable=False))
    op.add_column('rating_action', sa.Column('rating_type', sa.String(length=30), nullable=True))
    op.add_column('rating_action', sa.Column('rating_expiry', sa.Date(), nullable=True))
    op.add_column('rating_action', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('rating_action', sa.Column('source_name', sa.Text(), nullable=True))
    op.add_column('rating_action', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('rating_action', sa.Column('retrieved_date', sa.Date(), nullable=True))
    op.drop_constraint(op.f('rating_action_provenance_id_fkey'), 'rating_action', type_='foreignkey')
    op.drop_column('rating_action', 'provenance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_action', sa.Column('provenance_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('rating_action_provenance_id_fkey'), 'rating_action', 'provenance', ['provenance_id'], ['provenance_id'])
    op.drop_column('rating_action', 'retrieved_date')
    op.drop_column('rating_action', 'source_url')
    op.drop_column('rating_action', 'source_name')
    op.drop_column('rating_action', 'notes')
    op.drop_column('rating_action', 'rating_expiry')
    op.drop_column('rating_action', 'rating_type')
    op.drop_column('rating_action', 'action_date_is_estimated')
    op.add_column('product_snapshot', sa.Column('provenance_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('product_snapshot', sa.Column('tenor_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('product_snapshot', sa.Column('indicative_rate_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('product_snapshot_provenance_id_fkey'), 'product_snapshot', 'provenance', ['provenance_id'], ['provenance_id'])
    op.alter_column('product_snapshot', 'collateral_required',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('product_snapshot', 'product_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('product_snapshot', 'retrieved_date')
    op.drop_column('product_snapshot', 'source_url')
    op.drop_column('product_snapshot', 'source_name')
    op.drop_column('product_snapshot', 'notes')
    op.drop_column('product_snapshot', 'confidence')
    op.drop_column('product_snapshot', 'interest_rate_description')
    op.drop_column('product_snapshot', 'max_tenor_days')
    op.drop_column('product_snapshot', 'min_tenor_days')
    op.drop_column('product_snapshot', 'ticket_currency')
    op.add_column('portfolio_snapshot', sa.Column('provenance_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('portfolio_snapshot_provenance_id_fkey'), 'portfolio_snapshot', 'provenance', ['provenance_id'], ['provenance_id'])
    op.alter_column('portfolio_snapshot', 'provisioning_charge',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'stage_3_balance',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'stage_2_balance',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'stage_1_balance',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'net_loans',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'gross_loans',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.drop_column('portfolio_snapshot', 'retrieved_date')
    op.drop_column('portfolio_snapshot', 'source_url')
    op.drop_column('portfolio_snapshot', 'source_name')
    op.drop_column('portfolio_snapshot', 'notes')
    op.drop_column('portfolio_snapshot', 'confidence')
    op.drop_column('portfolio_snapshot', 'unit')
    op.drop_column('portfolio_snapshot', 'period_type')
    op.add_column('portfolio_mix', sa.Column('provenance_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('portfolio_mix_provenance_id_fkey'), 'portfolio_mix', 'provenance', ['provenance_id'], ['provenance_id'])
    op.alter_column('portfolio_mix', 'amount',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.drop_column('portfolio_mix', 'retrieved_date')
    op.drop_column('portfolio_mix', 'source_url')
    op.drop_column('portfolio_mix', 'source_name')
    op.drop_column('portfolio_mix', 'notes')
    op.drop_column('portfolio_mix', 'confidence')
    op.add_column('industry_aggregate', sa.Column('provenance_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('industry_aggregate', sa.Column('total_credit', sa.NUMERIC(precision=24, scale=2), autoincrement=False, nullable=True))
    op.add_column('industry_aggregate', sa.Column('sectoral_breakdown', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('industry_aggregate', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('industry_aggregate', sa.Column('npl_ratio_industry', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('industry_aggregate_provenance_id_fkey'), 'industry_aggregate', 'provenance', ['provenance_id'], ['provenance_id'])
    op.drop_column('industry_aggregate', 'retrieved_date')
    op.drop_column('industry_aggregate', 'source_url')
    op.drop_column('industry_aggregate', 'source_name')
    op.drop_column('industry_aggregate', 'notes')
    op.drop_column('industry_aggregate', 'confidence')
    op.drop_column('industry_aggregate', 'unit')
    op.drop_column('industry_aggregate', 'value')
    op.drop_column('industry_aggregate', 'metric')
    op.add_column('disbursement_metric', sa.Column('provenance_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('disbursement_metric_provenance_id_fkey'), 'disbursement_metric', 'provenance', ['provenance_id'], ['provenance_id'])
    op.alter_column('disbursement_metric', 'disbursement_volume',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.drop_column('disbursement_metric', 'retrieved_date')
    op.drop_column('disbursement_metric', 'source_url')
    op.drop_column('disbursement_metric', 'source_name')
    op.drop_column('disbursement_metric', 'notes')
    op.drop_column('disbursement_metric', 'metric_description')
    op.drop_column('disbursement_metric', 'unit')
    op.drop_column('disbursement_metric', 'period_type')
    op.add_column('capital_market_instrument', sa.Column('provenance_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('capital_market_instrument_provenance_id_fkey'), 'capital_market_instrument', 'provenance', ['provenance_id'], ['provenance_id'])
    op.alter_column('capital_market_instrument', 'issue_size',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=24, scale=2),
               existing_nullable=True)
    op.drop_column('capital_market_instrument', 'retrieved_date')
    op.drop_column('capital_market_instrument', 'source_url')
    op.drop_column('capital_market_instrument', 'source_name')
    op.drop_column('capital_market_instrument', 'notes')
    op.drop_column('capital_market_instrument', 'confidence')
    op.drop_column('capital_market_instrument', 'issue_date')
    op.drop_column('capital_market_instrument', 'unit')
    op.drop_column('capital_market_instrument', 'series')
    op.drop_column('capital_market_instrument', 'issuer_name')
    # ### end Alembic commands ###
