"""widen period_type

Revision ID: e66463e9d317
Revises: 291dfd768085
Create Date: 2026-08-22 16:08:18.777410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e66463e9d317'
down_revision: Union[str, None] = '291dfd768085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disbursement_metric', 'period_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('portfolio_snapshot', 'period_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_snapshot', 'period_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('disbursement_metric', 'period_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
